[versions]
kotlin = "1.9.22"
dokka = "1.9.10"
maven-publish = "0.26.0"
git-versioning = "6.4.3"
ktor = "2.3.8"
slf4j = "2.0.12"
playwright = "1.41.2"
junit = "5.10.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
git-versioning = { id = "me.qoomon.git-versioning", version.ref = "git-versioning" }

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
playwright = { module = "com.microsoft.playwright:playwright", version.ref = "playwright" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
